### ISSUE TITLE
Wings advertise wrong IP to Panel

### ISSUE THREAD

**Issue by marcopaggioro** [pelican-dev/wings#100]
Hi,
I divide the description into two parts. First the working one and then the non-working one.
Running wings as systemd process or with docker image make different IPs appear in the allocations.

**WORKING ONE**
Wings as process
In `/etc/pelican/config.yml`:
```
docker:
  network:
    interface: 172.100.0.1
    dns:
    - 1.1.1.1
    - 1.0.0.1
    name: minecraft0
    ispn: false
    IPv6: true
    driver: bridge
    network_mode: minecraft0
    is_internal: false
    enable_icc: true
    network_mtu: 1500
    interfaces:
      v4:
        subnet: 172.100.0.0/16
        gateway: 172.100.0.1
      v6:
        subnet: fdba:17c8:6c94::/64
        gateway: fdba:17c8:6c94::1011
```

We can see that the gateway of wings is 172.100.0.1. 
I start wings as systemd process or with `sudo wings --debug` and in panel->nodes->allocations I can see the 172.100.0.1.
That's the **docker network gateway IP**

**NOT WORKING**
With the same configuration of wings I try to start not from CLI but from docker compose like that:
```
  mc_wings:
    container_name: mc_wings
    image: ghcr.io/pelican-dev/wings
    ports:
      - "8443:8443"
      - "2022:2022"
    environment:
      TZ: "Europe/Rome"
      WINGS_UID: 0
      WINGS_GID: 0
      WINGS_USERNAME: pelican
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/var/lib/docker/containers:/var/lib/docker/containers"
      - "/etc/pelican:/etc/pelican"
      - "/root/minecraft:/root/minecraft"
      - "/var/log/pelican:/var/log/pelican"
      - "/tmp/pelican:/tmp/pelican"
      - "/etc/letsencrypt:/etc/letsencrypt"
    tty: true
    networks:
      - minecraft0
    restart: unless-stopped


networks:
  minecraft0:
    name: minecraft0
    driver: bridge
    ipam:
      config:
        - subnet: "172.100.0.0/16"
          gateway: 172.100.0.1
    driver_opts:
      com.docker.network.bridge.name: minecraft0
```

You can see that /etc/pelican points to the file mentioned above.
If I go to the same section Panel->Nodes->Allocations I expect to see 172.100.0.1 as the gateway address but I can only see 172.100.0.2 that is **wings container address** that is not correct.

If I try to create a binding with 172.100.0.2 the server start fails. 
If i start wings with docker and I use an allocation (previously created) with 172.100.0.1 so the server starts and all works fine
